/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as SessionsIdSettingsRouteImport } from './routes/sessions.$id.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdSettingsRoute = SessionsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SessionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$id/settings': typeof SessionsIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$id/settings': typeof SessionsIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRouteWithChildren
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$id/settings': typeof SessionsIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions/$id'
    | '/sessions/new'
    | '/sessions/'
    | '/sessions/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/$id'
    | '/sessions/new'
    | '/sessions'
    | '/sessions/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/sessions/$id'
    | '/sessions/new'
    | '/sessions/'
    | '/sessions/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsIdRoute: typeof SessionsIdRouteWithChildren
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/settings': {
      id: '/sessions/$id/settings'
      path: '/settings'
      fullPath: '/sessions/$id/settings'
      preLoaderRoute: typeof SessionsIdSettingsRouteImport
      parentRoute: typeof SessionsIdRoute
    }
  }
}

interface SessionsIdRouteChildren {
  SessionsIdSettingsRoute: typeof SessionsIdSettingsRoute
}

const SessionsIdRouteChildren: SessionsIdRouteChildren = {
  SessionsIdSettingsRoute: SessionsIdSettingsRoute,
}

const SessionsIdRouteWithChildren = SessionsIdRoute._addFileChildren(
  SessionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsIdRoute: SessionsIdRouteWithChildren,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
