import { describe, it, expect, beforeEach } from 'vitest'
import { db, createSession, saveAIProfile } from '@/db'
import { exportSession, importSession } from '@/lib/import-export'
import type { SessionExport } from '@/lib/import-export'

beforeEach(async () => {
  await db.delete()
  await db.open()
})

/**
 * Build a minimal valid SessionExport for testing.
 * All IDs are synthetic; import regenerates them.
 */
function validExport(overrides?: Partial<SessionExport>): SessionExport {
  return {
    version: 1,
    exportedAt: new Date().toISOString(),
    session: {
      name: 'Test Session',
      description: 'Track campaign health and explain warning spikes.',
      pollIntervalMs: 30000,
      timeoutMs: 15000,
    },
    sources: [
      {
        id: 'src-1',
        name: 'Ad Campaign',
        key: 'ads',
        url: 'https://api.example.com/ads',
        queryParams: [{ key: 'limit', value: '10' }],
        enabled: true,
      },
    ],
    fieldMappings: [
      {
        id: 'map-1',
        sourceId: 'src-1',
        label: 'Spend',
        key: 'spend',
        jsonPath: 'campaign.spend',
        type: 'number',
      },
    ],
    derivedMetrics: [
      {
        id: 'dm-1',
        label: 'ROAS',
        key: 'roas',
        formula: 'amount / spend',
      },
    ],
    charts: [
      {
        id: 'chart-1',
        name: 'Campaign Overview',
        series: ['ads.spend', 'roas'],
      },
    ],
    warningRules: [
      {
        id: 'rule-1',
        name: 'Low ROAS',
        expression: 'roas < 1.2',
        severity: 'warning',
        enabled: true,
      },
    ],
    ...overrides,
  }
}

/**
 * Convert an export object into a mock File for importSession.
 */
function makeImportFile(data: SessionExport): File {
  const json = JSON.stringify(data, null, 2)
  return new File([json], 'session.json', { type: 'application/json' })
}

describe('importSession — validation', () => {
  it('imports a valid minimal export', async () => {
    const file = makeImportFile(validExport())
    const sessionId = await importSession(file)

    expect(sessionId).toBeDefined()
    expect(typeof sessionId).toBe('string')
    expect(sessionId.length).toBeGreaterThan(0)

    // Session exists
    const session = await db.sessions.get(sessionId)
    expect(session).toBeDefined()
    expect(session!.name).toBe('Test Session')
    expect(session!.description).toBe('Track campaign health and explain warning spikes.')
    expect(session!.status).toBe('paused')

    // Sources exist
    const sources = await db.sources.where('sessionId').equals(sessionId).toArray()
    expect(sources).toHaveLength(1)
    expect(sources[0].key).toBe('ads')

    // Field mappings exist
    const mappings = await db.fieldMappings.where('sourceId').equals(sources[0].id).toArray()
    expect(mappings).toHaveLength(1)
    expect(mappings[0].type).toBe('number')

    // Derived metrics exist
    const metrics = await db.derivedMetrics.where('sessionId').equals(sessionId).toArray()
    expect(metrics).toHaveLength(1)
    expect(metrics[0].key).toBe('roas')

    // Charts exist
    const charts = await db.charts.where('sessionId').equals(sessionId).toArray()
    expect(charts).toHaveLength(1)
    expect(charts[0].name).toBe('Campaign Overview')

    // Warning rules exist
    const rules = await db.warningRules.where('sessionId').equals(sessionId).toArray()
    expect(rules).toHaveLength(1)
    expect(rules[0].severity).toBe('warning')
  })

  it('strips secrets from imported sources (authConfig is none)', async () => {
    const file = makeImportFile(validExport())
    const sessionId = await importSession(file)

    const sources = await db.sources.where('sessionId').equals(sessionId).toArray()
    expect(sources).toHaveLength(1)
    expect(sources[0].authConfig).toEqual({ type: 'none' })
  })

  it('regenerates IDs (does not use imported ids)', async () => {
    const file = makeImportFile(validExport())
    const sessionId = await importSession(file)

    // IDs should be UUIDs regenerated by import
    expect(sessionId).not.toBe(validExport().session.name) // just a sanity: sessionId is not the name
    const sources = await db.sources.where('sessionId').equals(sessionId).toArray()
    expect(sources[0].id).not.toBe('src-1')
  })

  it('rejects invalid JSON and creates zero sessions', async () => {
    const badFile = new File(['not json at all'], 'bad.json', { type: 'application/json' })

    await expect(importSession(badFile)).rejects.toThrow('Invalid JSON file')

    const sessions = await db.sessions.toArray()
    expect(sessions).toHaveLength(0)
  })

  it('rejects invalid mapping type and creates zero sessions', async () => {
    const bad = validExport()
    // Cast to set invalid type
    const mappings = bad.fieldMappings as Array<Record<string, unknown>>
    mappings[0].type = 'date'

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })

    await expect(importSession(file)).rejects.toThrow('invalid type "date"')

    const sessions = await db.sessions.toArray()
    expect(sessions).toHaveLength(0)
  })

  it('rejects invalid warning severity and creates zero sessions', async () => {
    const bad = validExport()
    const rules = bad.warningRules as Array<Record<string, unknown>>
    rules[0].severity = 'fatal'

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })

    await expect(importSession(file)).rejects.toThrow('invalid severity "fatal"')

    const sessions = await db.sessions.toArray()
    expect(sessions).toHaveLength(0)
  })

  it('rejects duplicate source keys and creates zero sessions', async () => {
    const bad = validExport()
    bad.sources.push({
      id: 'src-2',
      name: 'Ads Duplicate',
      key: 'ads', // same key as the first source
      url: 'https://api.example.com/ads2',
      queryParams: [],
      enabled: true,
    })

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })

    await expect(importSession(file)).rejects.toThrow('duplicate key "ads"')

    const sessions = await db.sessions.toArray()
    expect(sessions).toHaveLength(0)
  })

  it('rejects field mapping referencing missing sourceId and creates zero sessions', async () => {
    const bad = validExport()
    const mappings = bad.fieldMappings as Array<Record<string, unknown>>
    mappings[0].sourceId = 'nonexistent-source'

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })

    await expect(importSession(file)).rejects.toThrow('does not match any source')

    const sessions = await db.sessions.toArray()
    expect(sessions).toHaveLength(0)
  })

  it('rejects missing version', async () => {
    const bad = validExport() as unknown as Record<string, unknown>
    delete bad.version

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('Unsupported export version')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects empty session name', async () => {
    const bad = validExport()
    ;(bad.session as Record<string, unknown>).name = ''

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('non-empty string')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects non-string session description when present', async () => {
    const bad = validExport()
    ;(bad.session as Record<string, unknown>).description = 123

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('Session description must be a string when present')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects pollIntervalMs < 5000', async () => {
    const bad = validExport()
    ;(bad.session as Record<string, unknown>).pollIntervalMs = 4000

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('at least 5s')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects timeout above 80% of interval', async () => {
    const bad = validExport()
    ;(bad.session as Record<string, unknown>).pollIntervalMs = 5000
    ;(bad.session as Record<string, unknown>).timeoutMs = 4500

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('80% of the poll interval')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects empty sources array', async () => {
    const bad = validExport()
    bad.sources = []

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('At least one source')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('imports multiple sources with field mappings', async () => {
    const data = validExport()
    data.sources.push({
      id: 'src-2',
      name: 'Crowdfunding',
      key: 'crowdfunding',
      url: 'https://api.example.com/fund',
      queryParams: [],
      enabled: true,
    })
    data.fieldMappings!.push({
      id: 'map-2',
      sourceId: 'src-2',
      label: 'Amount',
      key: 'amount',
      jsonPath: 'campaign.amount',
      type: 'number',
    })

    const file = new File([JSON.stringify(data)], 'session.json', { type: 'application/json' })
    const sessionId = await importSession(file)

    const sources = await db.sources.where('sessionId').equals(sessionId).toArray()
    expect(sources).toHaveLength(2)

    const allMappings = await db.fieldMappings.toArray()
    expect(allMappings).toHaveLength(2)
  })

  it('rejects invalid source key format', async () => {
    const bad = validExport()
    ;(bad.sources[0] as Record<string, unknown>).key = 'Ads-1!'

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('invalid key')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })

  it('rejects invalid source URL', async () => {
    const bad = validExport()
    ;(bad.sources[0] as Record<string, unknown>).url = 'not-a-url'

    const file = new File([JSON.stringify(bad)], 'session.json', { type: 'application/json' })
    await expect(importSession(file)).rejects.toThrow('invalid URL')
    expect(await db.sessions.toArray()).toHaveLength(0)
  })
})

describe('exportSession', () => {
  it('includes session description in export', async () => {
    const session = await createSession({
      name: 'Export Session',
      description: 'Explain ad efficiency and donation trends.',
    })

    await db.sources.add({
      id: 'src-1',
      sessionId: session.id,
      key: 'ads',
      name: 'Ads',
      type: 'http-poll',
      url: 'https://api.example.com/ads',
      queryParams: [],
      authConfig: { type: 'bearer', token: 'secret-token' },
      enabled: true,
      createdAt: new Date().toISOString(),
    })

    const exported = await exportSession(session.id)
    expect(exported.session.description).toBe('Explain ad efficiency and donation trends.')
  })

  it('does not include ai profiles or chat history in export payload', async () => {
    const session = await createSession({
      name: 'Export Session',
      description: 'Export only session config.',
    })

    await db.sources.add({
      id: 'src-1',
      sessionId: session.id,
      key: 'ads',
      name: 'Ads',
      type: 'http-poll',
      url: 'https://api.example.com/ads',
      queryParams: [],
      authConfig: { type: 'none' },
      enabled: true,
      createdAt: new Date().toISOString(),
    })

    await saveAIProfile({
      name: 'Default profile',
      baseUrl: 'https://openrouter.ai/api/v1/chat/completions',
      apiKey: 'secret-key',
      model: 'openai/gpt-4.1-mini',
      transport: 'direct',
    })

    await db.sessionChatMessages.add({
      id: 'chat-1',
      sessionId: session.id,
      role: 'user',
      content: 'Tell me about this session.',
      createdAt: new Date().toISOString(),
    })

    const exported = await exportSession(session.id)
    expect(exported).not.toHaveProperty('aiProfiles')
    expect(exported).not.toHaveProperty('sessionChatMessages')
    expect(JSON.stringify(exported)).not.toContain('secret-key')
    expect(JSON.stringify(exported)).not.toContain('Tell me about this session.')
  })
})
